from odoo import models, fields, api


class ProductTemplateCustom(models.Model):
    _inherit = 'product.template'

    abk_uom_class_id = fields.Char('UOM Class')
    abk_ium = fields.Char('Inventory UM')
    abk_sales_um = fields.Char('Sales UM')
    abk_purchase_UM = fields.Char('Purchase UM')
    abk_prod_code = fields.Char('Group')
    abk_class_id = fields.Char('Class')
    abk_commodity_code = fields.Char('HS Commodity Code')
    abk_on_hold = fields.Char('Hold')
    abk_on_hold_date = fields.Char('Hold Date')
    abk_on_hold_reason_code = fields.Char('Hold Reason Code')
    abk_track_lots = fields.Char('Track Lots')
    abk_track_dimension = fields.Char('Track Dimension UOMs')
    abk_non_stock = fields.Char('Non-Stock Item')
    abk_inactive = fields.Char('Inactive')
    abk_mfg_comment = fields.Char('Manufacturing Comment')
    abk_pur_comment = fields.Char('Purchase Comment')
    abk_brand = fields.Char('Brand')
    abk_sub_brand = fields.Char('Sub-Brand')
    abk_co_warehouse = fields.Char('CO Warehouse')
    abk_grs_weight = fields.Char('GRS Weight(g)')
    abk_fsc_paper_weight = fields.Char('FSC Paper Weight (kg)')
    abk_fsc_claim = fields.Char('FSC Claim')
    abk_agent = fields.Char('Agent')
    abk_fk_lookup = fields.Char('F/K Lookup')
    abk_wo_salesman = fields.Char('WO-Salesman')
    abk_plant = fields.Char('Site')
    abk_prim_whse = fields.Char('Primary Warehouse')
    abk_minimum_qty = fields.Integer('Min On-Hand')
    abk_maximum_qty = fields.Integer('Max On-Hand')
    abk_safety_qty = fields.Char('Safety Stock')
    abk_reorder_level = fields.Integer('Re-Order to Max')
    abk_minorder_qty = fields.Integer('Min Order Qty')
    abk_lead_time = fields.Datetime('Lead Time')
    abk_production_lead_time = fields.Datetime('Production Lead Time')
    abk_generate_sugg = fields.Char('Generate PO Suggestions')
    abk_backflush = fields.Char('BackFlush')
    abk_prim_bin_num = fields.Char('Bin')

    abk_part_length = fields.Float('Part Length')
    abk_part_height = fields.Float('Part Height')
    abk_part_width = fields.Float('Part Width')

    # existing
    abk_part_num = fields.Char('Part')
    abk_part_description = fields.Text('Description')
    abk_type_code = fields.Char('Type')

    # add fields import product
    abk_custno = fields.Char('Customer No')
    abk_custsname = fields.Char('Customer Name')
    abk_infordate = fields.Datetime('Infor Date')
    abk_sizew1 = fields.Char('Size W1')
    abk_sizew2 = fields.Char('Size W2')
    abk_sizew = fields.Char('Size W')
    abk_sizel = fields.Char('Size L')
    abk_sizel1 = fields.Char('Size L1')
    abk_sizel2 = fields.Char('Size L2')
    abk_sizeunit = fields.Char('Size Unit')
    abk_itemsize = fields.Char('Item Size')
    abk_type1 = fields.Char('Type 1')
    abk_type2 = fields.Char('Type 2')
    abk_type3 = fields.Char('Type 3')
    abk_type4 = fields.Char('Type 4')
    abk_type5 = fields.Char('Type 5')
    abk_stockamt = fields.Char('Stock Amount')
    abk_unit = fields.Char('Unit')
    abk_producttype = fields.Char('Product Type')
    abk_adgetype = fields.Char('Adge Type')
    abk_machine = fields.Char('Machine')
    abk_process = fields.Char('Process')
    abk_paper = fields.Char('Paper')
    abk_fcolourno = fields.Char('Fcolour No')
    abk_fcolour = fields.Char('Fcolour')
    abk_bcolourno = fields.Char('Bcolour No')
    abk_bcolour = fields.Char('Bcolour')
    abk_trimsize1 = fields.Char('Trimsize1')
    abk_trimsize2 = fields.Char('Trimsize2')
    abk_trimunit = fields.Char('Trimunit')
    abk_remake = fields.Char('Remake')
    abk_remake2 = fields.Char('Remake 2')

